import timer from "./modules/timer";
import menu from "./modules/menu";
import modal from "./modules/modal";
import scroll from "./modules/scroll";
import calcValidation from "./modules/calcValidation";
import formsValidation from "./modules/formsValidation";
import tabs from "./modules/tabs";
import addDot from "./modules/addDots";
import slider from "./modules/slider";
import sendForm from "./modules/sendForm";

timer("10 december 2021");
menu();
modal();
scroll();
calcValidation();
formsValidation();
tabs();
addDot();
slider();
sendForm();
